# Generated by Django 4.1 on 2023-02-01 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='band',
            name='biography',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Metal', 'Metal'), ('Jazz', 'Jazz'), ('Blues', 'Blues'), ('Country', 'Country'), ('Classical', 'Classical'), ('Folk', 'Folk'), ('Electronic', 'Electronic'), ('Hip Hop', 'Hip Hop'), ('Reggae', 'Reggae'), ('Rap', 'Rap'), ('Soul', 'Soul'), ('Disco', 'Disco'), ('Punk', 'Punk'), ('Indie', 'Indie'), ('R&B', 'Rnb'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='band',
            name='officiel_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='year_formed',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)]),
            preserve_default=False,
        ),
    ]
