# Generated by Django 4.1 on 2023-02-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_sold_listing_types_listing_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sold',
            field=models.BooleanField(default=True),
        ),
    ]
