# Generated by Django 4.1 on 2023-02-01 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sold',
            new_name='Nosold',
        ),
    ]
