# Generated by Django 4.1 on 2023-02-01 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_band_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
    ]
